 INSERT INTO bears (id, name, age, sex, color, temperament, alive)
 VALUES 
  (1, 'Mr.Chocolate', 10, 'M', 'Black', 'Tasty', true)  
  (2, 'Rowdy', 12, 'F', 'White', 'Tough', true) 
  (3, 'Tabitha', 22, 'F', 'Black', 'Pretty', true) 
  (4, 'Sergeant Brown', 22, 'M', 'Black', 'Huge', true) 
  (5, 'Melissa', 19, 'F', 'Brown', 'Beauty', true) 
  (6, 'Grinch', 20, 'M', 'Brown', 'Ugly', False) 
  (7, 'Wendy', 22, 'F', 'Brown', 'Ugly', False) 
  (NULL, 0, 22, 'F', 'Brown', 'Ugly', 2) 
